### ISSUE TITLE
"geospatial kosher" term still shows in data profile mouseover text in Biocache

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/data-quality-filter-service#14]
If you mouseover the text "Exclude spatially suspect records" under the standard ALA General data profile in a Biocache search, the following explanation appears: "Exclude records with a spatially suspect (geospatial kosher) flag." As geospatial-kosher has become a deprecated term, it should be replaced with "spatially valid": https://support.ala.org.au/support/solutions/articles/6000249565-spatially-valid-flag.

![Image](https://github.com/AtlasOfLivingAustralia/data-quality-filter-service/assets/57081387/b7289602-48c7-47b2-8ba6-fcdc60b9a024)

**Comment by adam-collins** [comment]
@peggynewman I think this issue is for you, editing a data quality profile.

**Comment by adam-collins** [comment]
Done. Please wait 12hrs for caches to clear.
