### ISSUE TITLE
Data Quality filter contentTypes filtering problem

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/data-quality-filter-service#15]
In an all data query (https://biocache.ala.org.au/occurrences/search?q=) with the DQ filters on, there are an expected 1.1 million- ish records excluded based on record type (ie basis of record).

When you click on the filter to see the excluded records, the query doesn't return the 1.1 million-ish records, instead only 279 records, and this seems to be related to how the query is parsed. The FOSSIL_SPECIMEN make it in, but not the "Environmental DNA" contentType

https://biocache.ala.org.au/occurrence/search?q=&qualityProfile=ALA&disableAllQualityFilters=true&fq=basisOfRecord%3A%22FOSSIL_SPECIMEN%22+%28%2BbasisOfRecord%3AMATERIAL_SAMPLE+%2BcontentTypes%3AEnvironmental+DNA%29#tab_mapView

**Comment by adam-collins** [comment]
The moment we entered anything remotely complex into a `filter value` the chance that this would work was reduced. Given the very wide variety of inputs possible, this is the most robust solution:
 
1. Added a field to QualityCategory for the inverseFilter. This permits overriding the value that is automatically generated and sometimes incorrect. 
2. Updated the UI to put in a warning when the inverseFilter may be required. 


![Image](https://github.com/AtlasOfLivingAustralia/data-quality-filter-service/assets/8031500/0dfa797b-cc04-4dcf-a69a-412bf57548ca)



In test, please test.

**Comment by kylie-m** [comment]
Thanks Adam!

@peggynewman I gave this a try on test and it's looking ok to me. Since you initially raised it, could you also give it a try and confirm you're happy with the changes?
