### ISSUE TITLE
Improve the "exclude duplicate records" filter

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/data-quality-filter-service#2]
As [reported by a user](https://support.ehelp.edu.au/a/tickets/115301), the duplicate filters are removing both representative and associated versions of the records from different datasets. The expected output is to only remove the associated version.

The filter to do this is: `&fq=-(duplicate_status%3A"ASSOCIATED"+AND+duplicateType%3A"DIFFERENT_DATASET")` however the admin UI cannot generate this style of filter.

Suggested the UI have an option to allow a raw filter to be specified.

**Comment by peggynewman** [comment]
Alex H worked on this change - I think it might be in the [manual feauture branch](https://github.com/AtlasOfLivingAustralia/data-quality-filter-service/tree/feature/manual_input)

The brackets need to be in the query and only a manually input filter can do that. If this can go into databox I can test it.

https://user-images.githubusercontent.com/1271932/176393481-1607f627-b628-4ac3-bbcd-0d92470e19b6.mov

**Comment by peggynewman** [comment]
I've tested this change successfully and run through the functional testing at https://confluence.csiro.au/display/ALASD/Data+Quality+Filters+Service ... this change is ready for CAB
